#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "levs-commands/main_commands.typ": *
#import "custom_commands.typ": *
#import "@preview/cheq:0.2.2": checklist
#show: checklist

#show: thmrules
#show: eqrules
#set math.equation(numbering: none)


#show: arkheion.with(
  title: "Characterizing Datasets: Hardness, Learning, and More",
  authors: (
    (
      name: "Lev Stambler",
      email: "lev@tearlabs.ai",
      affiliation: [Tear Labs Corp. \ University of Maryland, College Park],
    ),
  ),
  abstract: [
    #align(left)[
      We give a native categorical Goldreich--Levin algorithm for a dataset distribution generated by an autoregressive model.
      From one fixed real prefix, the model's sampling probabilities induce a non-uniform rollout law on $ZZ_q^n$, while its raw next-token probabilities label the generated continuations.
      Processing coordinates newest-first turns every conditional-sampling request into exact suffix regeneration from a reusable KV-cached left prefix.
      We prove the categorical character identities, conditional-bucket completeness and monotonicity, the weighted level-mass formula for an arbitrary rollout law, and an unbiased paired-suffix estimator.
      A single native length-$q$ Fourier transform estimates all categorical children of a live bucket, giving sample complexity $O(n N log(n q N/delta)/tau^4)$ for live spectral width $N$.
      The guarantee recovers heavy coefficients of arbitrary token-degree through $n=128$ without encoding tokens into Boolean variables or evaluating the label outside the model-generated distribution.
    ]
  ],
  //keywords: ("First keyword", "Second keyword", "etc."),
  date: "July 8, 2026",
)

// #include "sections/intro.typ"
#include "sections/prelims.typ"
#include "sections/gl.typ"
#include "sections/related.typ"
#include "sections/conc.typ"

#bibliography(("levs-bibs/crypto.bib", "levs-bibs/ai-complexity.bib",), style: "association-for-computing-machinery")

#include "sections/appendix.typ"
