#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "levs-commands/main_commands.typ": *
#import "custom_commands.typ": *
#import "@preview/cheq:0.2.2": checklist
#show: checklist

#show: thmrules
#show: eqrules
#set math.equation(numbering: none)


#show: arkheion.with(
  title: "Characterizing Datasets: Hardness, Learning, and More",
  authors: (
    (
      name: "Lev Stambler",
      email: "lev@tearlabs.ai",
      affiliation: [Tear Labs Corp. \ University of Maryland, College Park],
    ),
  ),
  abstract: [
    #align(left)[
      We give a native categorical Goldreich--Levin algorithm for a dataset distribution generated by an autoregressive model.
      A random real corpus context followed by an autoregressive rollout induces a non-uniform law on $ZZ_q^n$, while the model's full tokenizer-level next-token distribution labels the continuation.
      Processing coordinates newest-first turns every conditional-sampling request into exact suffix regeneration from a reusable KV-cached real-and-generated left prefix.
      We prove the categorical character identities, conditional-bucket completeness and monotonicity, the weighted level-mass formula for an arbitrary rollout law, and an unbiased paired-suffix estimator.
      One native length-$q$ inverse Fourier transform per live parent estimates all categorical children, giving sample complexity $O(n N log(n q N/delta)/tau^4)$ for live spectral width $N$.
      The vector theorem recovers prefix-conditional RMS character correlations of arbitrary token support through $n=128$ without encoding tokens into Boolean variables; compression and top-token agreement are evaluated empirically.
    ]
  ],
  //keywords: ("First keyword", "Second keyword", "etc."),
  date: "July 13, 2026",
)

// #include "sections/intro.typ"
#include "sections/prelims.typ"
#include "sections/gl.typ"
#include "sections/experiments.typ"
#include "sections/fourier_correlation_memory.typ"
#include "sections/part2_large_q_sft.typ"
#include "sections/related.typ"
#include "sections/conc.typ"

#bibliography(("levs-bibs/crypto.bib", "levs-bibs/ai-complexity.bib",), style: "association-for-computing-machinery")

#include "sections/appendix.typ"
