#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "../levs-commands/main_commands.typ": *
#import "../custom_commands.typ": *
#import "@preview/cheq:0.2.2": checklist
#show: checklist

#show: thmrules
#show: eqrules
#set math.equation(numbering: none)


#show: arkheion.with(
  title: "Characterizing Datasets: Hardness, Learning, and More",
  authors: (
    (
      name: "Lev Stambler",
      email: "lev@tearlabs.ai",
      affiliation: [Tear Labs Corp. \ University of Maryland, College Park],
    ),
  ),
  abstract: [
    #align(left)[
      We develop Fourier analysis of functions evaluated on datasets: expectations are taken over the
      dataset law rather than a product measure.  Dataset coefficients relate to uniform coefficients of
      the lifted function by a single density constant; the mass identity replaces Parseval, normalized
      characters restore constant-free Parseval, closeness, and reconstruction, and the low-degree learning
      algorithm survives with one essential scaling.
      When the dataset law is generated by an autoregressive model, the model itself supplies conditional
      access: a cached realized prefix can be forked to resample independent suffixes from the exact
      conditional law.  Processing coordinates newest-first turns every conditional-sampling request into
      exact suffix regeneration.  We prove the categorical character identities, conditional-bucket
      completeness and monotonicity, the weighted level-mass formula for an arbitrary rollout law, an
      unbiased paired-suffix estimator, and an all-children categorical DFT.  One native length-$q$ inverse
      Fourier transform per live parent estimates all categorical children, giving sample complexity
      $O(n N log(n q N/delta)/tau^4)$ for live spectral width $N$, with no low-degree assumption and no
      binary encoding of tokens; the vector theorem recovers prefix-conditional RMS character correlations
      of arbitrary token support over random real contexts.
      We also prove an oracle separation: uniform-law sparse Fourier transforms target dataset coefficients
      only with chosen density-and-label point queries, and prefix-conditional sampling cannot substitute
      for affine membership conditions.  Finally, we characterize which Fourier coefficients
      position-shared correlation memories compute, and how their categorical degree grows with depth.
    ]
  ],
  //keywords: ("First keyword", "Second keyword", "etc."),
  date: "August 3, 2026",
)

#include "sections/intro.typ"
#include "sections/dataset_fourier.typ"
#include "sections/generative_oracle.typ"
#include "sections/oracle_separation.typ"
#include "sections/correlation_memory.typ"
#include "sections/related.typ"
#include "sections/discussion.typ"
#include "sections/conclusion.typ"

#bibliography(("../levs-bibs/crypto.bib", "../levs-bibs/ai-complexity.bib",), style: "association-for-computing-machinery")

#include "sections/appendix.typ"
