#import "../../levs-commands/main_commands.typ": *
#show: thmrules
#show: eqrules
#set math.equation(numbering: none)

= Introduction

Fourier analysis of Boolean functions — and of functions on product probability spaces generally — takes
expectations over a product measure: every coordinate is resampled independently.
A trained model evaluated on its own rollouts, a corpus of token sequences, or a table of feature vectors
is not a product measure.  It is a finite or finitely-sampled set inside an ambient product space, and the
functions we care about are only evaluated on it.
This paper develops the Fourier theory of such *datasets*: we keep the characters of the ambient product
space, but take every expectation over the dataset law.

Two structural facts organize the theory.
First, dataset Fourier coefficients are related to ordinary uniform Fourier coefficients of the *lifted*
function by a single density constant (@lem:lift).  Every classical fact therefore translates into a
dataset fact with an explicit, exact correction: the mass identity (@lem:mass) replaces Parseval, the
normalized characters restore a constant-free Parseval and reconstruction (@lem:dataset-parseval), and the
low-degree learning algorithm survives with one essential scaling (@thm:learning-low-degree).

Second, when the dataset law is generated by an autoregressive model, the model itself supplies the one
resource that heavy-coefficient search needs beyond samples: conditional access.
After any realized left prefix, the same model resamples independent continuation suffixes from the exact
conditional law, at the cost of a forked KV cache.
Processing coordinates *newest-first* turns every conditional-sampling request of Goldreich--Levin into
ordinary suffix regeneration.
Our main theorem (@thm:ar-qary-gl, @thm:random-context-vector-gl) is a categorical Dataset Goldreich--Levin
algorithm over $ZZ_q^n$, where one token position is one variable regardless of $q$: no binary encoding of
tokens, and no low-degree assumption.  One length-$q$ inverse Fourier transform per live parent estimates
all $q$ categorical children from the same suffix pairs, and the sample complexity is governed by the live
spectral width $N$ of the rollout law rather than by any degree bound.

The generative oracle is also strictly weaker than the oracles assumed by finite-group sparse Fourier
transforms.  We prove the exact reduction: uniform-law SFT algorithms target dataset coefficients only when
their oracle answers *chosen* points with both density and label (@prop:affine-alias), and the vector
energy hashes they peel are paired expectations (@prop:affine-pair).  Autoregressive continuation can
condition only on coordinate-aligned suffix events, so it cannot supply affine membership conditions for
generic $M$, and the coordinate-aligned surrogate differs from the true bucket under any non-uniform law
(@sec:oracle-separation).  The reverse-time tree is therefore not an artifact of a weak algorithm; it is
what the oracle buys.

Finally, we ask which structural hypotheses could replace an explicit list of heavy characters.
A position-shared correlation memory — linear attention with learned decay — ties together every
same-lag degree-two coefficient with one parameter per decay mode, and depth grows the represented
categorical degree at most by a factor of three per layer (@sec:fourier-correlation-memory).
This is a representation statement, not a learning claim: it identifies exactly which Fourier
coefficients such a stack computes, and what remains open.

*Contributions.*
+ A complete Fourier dictionary for functions on datasets: the lift, the mass identity, normalized
  Parseval/closeness/reconstruction, dataset sensitivity, and low-degree learning with the exact density
  scaling (@sec:dataset-fourier).
+ Categorical Dataset Goldreich--Levin for autoregressive rollout laws with prefix-conditional sampling:
  the conditional-bucket identities, the weighted level-mass formula, the unbiased paired-suffix estimator,
  the all-children DFT, and fixed-prefix and random-context vector theorems with live-width sample
  complexity (@sec:generative-oracle).
+ An oracle separation between prefix-conditional sampling and the chosen-point oracles of AGS, $q$-SFT,
  and GFast, including the affine alias and pair identities (@sec:oracle-separation).
+ Degree-growth representation theory for position-shared Fourier correlation memories
  (@sec:fourier-correlation-memory).

The paper is deliberately theoretical.  Every empirical question it raises — whether a concrete teacher's
spectrum is live-width-bounded, whether recovered characters compress, whether a correlation memory is
narrower than a character list — is stated as open in @sec:discussion.
