[project]
name = "v3-dllm-monarch"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "accelerate==1.11.0",
  "datasets==4.2.0",
  "deepspeed==0.18.0",
  "liger-kernel==0.8.1",
  "matplotlib>=3.10,<4",
  "nvidia-ml-py>=13.580",
  "omegaconf>=2.3,<3",
  "peft==0.17.1",
  "pytest>=8.4",
  "rich>=14,<15",
  "safetensors>=0.5",
  "sentencepiece==0.2.0",
  "setuptools>=80,<81",
  "torch==2.10.0",
  "torchmetrics>=1.8,<2",
  "transformers==4.57.0",
  "trl==0.24.0",
  "tyro>=0.9,<1",
  "wandb>=0.22,<0.30",
]

[tool.uv]
package = false
